services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-qa-lab
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: qa_lab
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data: